<ul id="navigationMenu">
	<li>
		<a href="<?php echo $this->url(array('controller'=>'cms-admin'),'default',true); ?>" class="leftStart">
			<span>Strona główna</span>
		</a>
		<p class="onLineStart">Strona główna</p>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'options'),'default',true); ?>" class="leftMainOptions">
			<span>Ustawienia główne</span>
		</a>
		<p class="onLineStart">Ustawienia główne</p>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'user'),'default',true); ?>" class="leftUser">
			<span>Profil użytkownika</span>
		</a>
		<p class="onLineStart">Profil użytkownika</p>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'list','section'=>'category'),'default',true); ?>" class="leftCategory">
			<span>Kategorie</span>
		</a>
		<p class="onLineStart">Kategorie</p>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'list','section'=>'article'),'default',true); ?>" class="leftArticle">
			<span>Artykuły</span>
		</a>
		<p class="onLineStart">Artykuły</p>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'list-product'),'default',true); ?>" class="leftProduct">
			<span>Produkty</span>
		</a>
		<p class="onLineStart">Produkty</p>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'list-newsletter'),'default',true); ?>" class="leftNewsletter">
			<span>Biuletyn</span>
		</a>
		<p class="onLineStart">Biuletyn</p>
	</li>
	<li>
		<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'list-sidebar'),'default'); ?>" class="leftSideBar">
			<span>Pasek boczny</span>
		</a>
		<p class="onLineStart">Pasek boczny</p>
	</li>
</ul>