<h1>News został dodany</h1>

<div class="backStyle">
	<ul>
		<li class="btnBack" id="btnBack">
			<a href="<?php echo $this->url(array('controller'=>'cms-admin'),'default',true) ?>"><span class="btnBackSpan">&nbsp;</span></a>
		</li>
		<li class="txtBack">
			<span>Główna</span>
		</li>
	</ul>
</div>
&nbsp;
<div class="backStyle">
	<ul>
		<li class="btnBack" id="btnBack">
			<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'list-newsletter'),'default',true) ?>"><span class="btnBackSpan">&nbsp;</span></a>
		</li>
		<li class="txtBack">
			<span>Powrót</span>
		</li>
	</ul>
</div>