<h1>
	Dane zostały zapisane pomyślnie:
	<?php switch ($this->section) {
		case 'category':
			echo 'nową KATEGORIE';
			break;
		case 'article':
			echo 'nowy ARTYKUŁ';
			break;
	} ?>
</h1>

<div class="backStyle">
	<ul>
		<li class="btnBack" id="btnBack">
			<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'list','section'=>$this->section),'default',true) ?>"><span class="btnBackSpan">&nbsp;</span></a>
		</li>
		<li class="txtBack">
			<span>Powrót</span>
		</li>
	</ul>
</div>