<h1>Dodaj 
	<?php if ($this->section == 'category')	echo 'KATEGORIE'; else echo 'ARTYKUŁ'; ?>:
</h1>
	<?php echo $this->form ?>
	
<div class="backStyle">
	<ul>
		<li class="btnBack" id="btnBack">
			<a href="<?php echo $this->url(array('controller'=>'cms-admin'),'default',true) ?>"><span class="btnBackSpan">&nbsp;</span></a>
		</li>
		<li class="txtBack">
			<span>Powrót</span>
		</li>
	</ul>
</div>