<div class="containerTitleSubPage">
	<div class="containerTitleSubPageLeft">
		<h1>Lista elementów paska bocznego:</h1>
	</div>
	<div class="containerTitleSubPageRight">
		<div class="addStyle">
			<ul>
				<li class="txtAdd">
					<span>Dodaj element do paska bocznego</span>
				</li>
				<li class="btnAdd" id="btnAddID">
					<a href="<?php echo $this->url(array('action'=>'new-sidebar'),'default') ?>"><span class="btnAddSpan">&nbsp;</span></a>
				</li>
			</ul>
		</div>
	</div>
</div>
<hr/>
<br />
<table id="listTable">
	<thead>
		<tr class="listTh">
			<th>Lp.</th>
			<th>Nazwa</th>
			<th>Status</th>
		</tr>
	</thead>
	<tbody>
<?php
	$count = 0;
	$result = 1;
	$ordinal = 1;
	foreach ($this->data as $sidebar) {
		if ($count == $result) {
			$result= $result+2;
			?>
		<tr class="listTr">
			<td class="tablePadding"><?php echo $ordinal ?></td>
			<td class="tablePadding"><a href="<?php echo $this->url(array('action'=>'sidebar','id'=>$sidebar['id_sidebar']),'default') ?>"><?php echo $sidebar['name_sidebar']; ?></a></td>
			<td class="tablePadding">
				<?php if ($sidebar['visibility_sidebar'] == 'false') {
					echo '<strong>Niewidoczny</strong>';
				}else echo 'Widoczny'; ?>
			</td>
		</tr>
			<?php
		}else{
	?>
		<tr>
			<td class="tablePadding"><?php echo $ordinal ?></td>
			<td class="tablePadding"><a href="<?php echo $this->url(array('action'=>'sidebar','id'=>$sidebar['id_sidebar']),'default') ?>"><?php echo $sidebar['name_sidebar']; ?></a></td>
			<td class="tablePadding">
				<?php if ($sidebar['visibility_sidebar'] == 'false') {
					echo '<strong>Niewidoczny</strong>';
				}else echo 'Widoczny'; ?>
			</td>
		</tr>
<?php
		}
		$count++;
		$ordinal++;
	}
?>
	</tbody>
</table>

<div class="backStyle">
	<ul>
		<li class="btnBack" id="btnBack">
			<a href="<?php echo $this->url(array('controller'=>'cms-admin'),'default',true); ?>"><span class="btnBackSpan">&nbsp;</span></a>
		</li>
		<li class="txtBack">
			<span>Powrót</span>
		</li>
	</ul>
</div>