<h1>Edytuj biuletyn (newsletter):</h1>
<?php echo $this->form; ?>
<?php echo $this->deleteForm; ?>

<div class="backStyle">
  <ul>
    <li class="btnBack" id="btnBack">
      <a href="<?php echo $this->url(array('action'=>'list-newsletter','controller'=>'cms-admin'),'default',true) ?>"><span class="btnBackSpan">&nbsp;</span></a>
    </li>
    <li class="txtBack">
      <span>Powrót</span>
    </li>
  </ul>
</div>