<h1>Edycja produktu: <?php echo $this->product['name_product'] ?></h1>

<?php echo $this->formCategory ?>

<?php echo $this->formAddedCategory ?>

<hr />

<?php echo $this->form ?>

<div class="backStyle">
	<ul>
		<li class="btnBack" id="btnBack">
			<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'list-product'),'default',true) ?>"><span class="btnBackSpan">&nbsp;</span></a>
		</li>
		<li class="txtBack">
			<span>Powrót</span>
		</li>
	</ul>
</div>