<h1>Edycja produktu: <?php echo $this->product['name_product'] ?></h1>

<?php echo $this->form ?>

<?php 
foreach ($this->wynik as $key) {
	echo $key['id_category'].' - '.$key['id_product'].'<br>';
}
 ?>

<div class="backStyle">
	<ul>
		<li class="btnBack" id="btnBack">
			<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'list-product'),'default',true) ?>"><span class="btnBackSpan">&nbsp;</span></a>
		</li>
		<li class="txtBack">
			<span>Powrót</span>
		</li>
	</ul>
</div>