<h1>Lista artykułów w <?php echo $this->nameSortedCategory['name_category'] ?>:</h1>
<hr />
<div id="cat_sort_info">
	<ul id="sortable" class="backgroundSortable">
		<?php
			foreach ($this->listArticle as $articles) {
				?>
				<li id="setArt-<?php echo $articles['id_article'] ?>" class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span><?php echo $articles['name_article'] ?>
					<span class="actions"><a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'edit','section'=>'article','id'=>$articles['id_article']),'default',true) ?>">Edytuj</a><a href="<?php echo $this->url(array('controller'=>'index','action'=>'articles','id_category'=>$this->categories,'id_article'=>$articles['id_article']),'default',true) ?>">Podgląd</a></span>
				</li>
				<?php
			}
		?>
	</ul>
</div>

<script type="text/javascript">
$('#sortable').sortable({
			update : function () { 
				var vieworder = $('#sortable').sortable('serialize'); 
				$('#cat_sort_info').load('/cms-admin/save-sorted-article/'+vieworder);
				$('#cat_sort_info').effect("pulsate", { times:3 }, 500);
			} 
		});
</script>

<h2 class="sortH2">Lista produktów w kategorii <?php echo $this->nameSortedCategory['name_category'] ?>:</h2>
<hr />
<div id="cat_sort_info_prod">
	<ul id="sortableProd" class="backgroundSortable">
		<?php
			foreach ($this->listProduct as $products) {
				?><li id="setProd-<?php echo $products['id_product'] ?>" class="ui-state-default"><span class="ui-icon ui-icon-arrowthick-2-n-s"></span><?php echo $products['name_product'] ?>
					<span class="actions"><a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'product','id'=>$products['id_product']),'default',true) ?>">Edytuj</a><a href="<?php echo $this->url(array('controller'=>'index','action'=>'product','id_product'=>$products['id_product']),'default',true) ?>">Podgląd</a></span>
				</li><?php
			}
		?>
	</ul>
</div>

<script type="text/javascript">
$('#sortableProd').sortable({
			update : function () { 
				var vieworder = $('#sortableProd').sortable('serialize'); 
				$('#cat_sort_info_prod').load('/cms-admin/save-product/'+vieworder);
				$('#cat_sort_info_prod').effect("pulsate", { times:3 }, 500);
			} 
		});
</script>

<div class="backStyle">
	<ul>
		<li class="btnBack" id="btnBack">
			<a href="<?php echo $this->url(array('controller'=>'cms-admin','action'=>'sort-sub-category','id'=>$this->nameSortedCategory['id_category']),'default',true) ?>"><span class="btnBackSpan">&nbsp;</span></a>
		</li>
		<li class="txtBack">
			<span>Powrót</span>
		</li>
	</ul>
</div>